package com.miniMart.model;
// Generated Jun 15, 2012 3:36:24 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.*;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name="Item"
    ,catalog="miniMart"
)
public class Item  implements java.io.Serializable {


     private long id;
     private String name;
     private String barcode;
     private Integer quantity;
     private Float price;
     private Integer minQty;
     private Integer maxQty;
     private Float gst;
     private Float gstPercent;
     private Integer cartonQty;
     private String category;

    public Item() {
    }

	
    public Item(long id, String name) {
        this.id = id;
        this.name = name;
    }
    public Item(long id, String name, String barcode, Integer quantity, Float price, Integer minQty, Integer maxQty, Float gst, Float gstPercent, Integer cartonQty, String category) {
       this.id = id;
       this.name = name;
       this.barcode = barcode;
       this.quantity = quantity;
       this.price = price;
       this.minQty = minQty;
       this.maxQty = maxQty;
       this.gst = gst;
       this.gstPercent = gstPercent;
       this.cartonQty = cartonQty;
       this.category = category;
    }
   
     @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="Id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="Name", nullable=false, length=125)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="Barcode", length=50)
    public String getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }
    
    @Column(name="Quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    
    @Column(name="Price", precision=12, scale=0)
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }
    
    @Column(name="Min_qty")
    public Integer getMinQty() {
        return this.minQty;
    }
    
    public void setMinQty(Integer minQty) {
        this.minQty = minQty;
    }
    
    @Column(name="Max_qty")
    public Integer getMaxQty() {
        return this.maxQty;
    }
    
    public void setMaxQty(Integer maxQty) {
        this.maxQty = maxQty;
    }
    
    @Column(name="Gst", precision=12, scale=0)
    public Float getGst() {
        return this.gst;
    }
    
    public void setGst(Float gst) {
        this.gst = gst;
    }
    
    @Column(name="Gst_percent", precision=12, scale=0)
    public Float getGstPercent() {
        return this.gstPercent;
    }
    
    public void setGstPercent(Float gstPercent) {
        this.gstPercent = gstPercent;
    }
    
    @Column(name="Carton_qty")
    public Integer getCartonQty() {
        return this.cartonQty;
    }
    
    public void setCartonQty(Integer cartonQty) {
        this.cartonQty = cartonQty;
    }
    
    @Column(name="Category", length=50)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }




}


