package com.miniMart.model;
// Generated Jun 15, 2012 3:36:24 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ItemSupplier generated by hbm2java
 */
@Entity
@Table(name="Item_Supplier"
    ,catalog="miniMart"
)
public class ItemSupplier  implements java.io.Serializable {


     private long suppItemId;
     private long supplierId;
     private long itemId;
     private int quantity;
     private float pricePerUnit;

    public ItemSupplier() {
    }

    public ItemSupplier(long suppItemId, long supplierId, long itemId, int quantity, float pricePerUnit) {
       this.suppItemId = suppItemId;
       this.supplierId = supplierId;
       this.itemId = itemId;
       this.quantity = quantity;
       this.pricePerUnit = pricePerUnit;
    }
   
     @Id 
    
    @Column(name="SuppItem_Id", unique=true, nullable=false)
    public long getSuppItemId() {
        return this.suppItemId;
    }
    
    public void setSuppItemId(long suppItemId) {
        this.suppItemId = suppItemId;
    }
    
    @Column(name="Supplier_Id", nullable=false)
    public long getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(long supplierId) {
        this.supplierId = supplierId;
    }
    
    @Column(name="Item_Id", nullable=false)
    public long getItemId() {
        return this.itemId;
    }
    
    public void setItemId(long itemId) {
        this.itemId = itemId;
    }
    
    @Column(name="Quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    
    @Column(name="Price_per_unit", nullable=false, precision=12, scale=0)
    public float getPricePerUnit() {
        return this.pricePerUnit;
    }
    
    public void setPricePerUnit(float pricePerUnit) {
        this.pricePerUnit = pricePerUnit;
    }




}


