package com.miniMart.model;
// Generated Jun 15, 2012 3:36:24 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name="Supplier"
    ,catalog="miniMart"
)
public class Supplier  implements java.io.Serializable {


     private long supplierId;
     private String name;

    public Supplier() {
    }

	
    public Supplier(long supplierId) {
        this.supplierId = supplierId;
    }
    public Supplier(long supplierId, String name) {
       this.supplierId = supplierId;
       this.name = name;
    }
   
     @Id 
    
    @Column(name="Supplier_Id", unique=true, nullable=false)
    public long getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(long supplierId) {
        this.supplierId = supplierId;
    }
    
    @Column(name="Name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


